apiVersion: v2
name: cagette
description: The Cagette Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "0.1.0"

sources:
  - https://github.com/gpenaud/cagette.git
  - https://github.com/gpenaud/helm-cagette.git

dependencies:
  - condition: mysql.enabled
    name: mysql
    version: 0.1.0

keywords:
  - application
  - web
  - http
  - amap

maintainers:
  - email: guillaume.penaud@gmail.com
    name: Guillaume Penaud
