apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
type: Opaque
stringData:
  mysql_password: {{ .Values.app.configuration.webapp.encrypted_mysql_password | decryptAES (.Values.aesKey | b64dec)}}
  smtp_user: {{ .Values.app.secrets.mailer.encrypted_smtp_user | decryptAES (.Values.aesKey | b64dec)}}
  smtp_password: {{ .Values.app.secrets.mailer.encrypted_smtp_password | decryptAES (.Values.aesKey | b64dec)}}
