apiVersion: v1
kind: Service
metadata:
  name: {{ include "cagette.fullname" . }}
  labels:
    {{- include "cagette.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - name: http
      port: {{ .Values.app.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    {{- include "cagette.selectorLabels" . | nindent 4 }}
